### ISSUE TITLE
Initialization fails with github token

### ISSUE THREAD

**Issue by dbirman** [scratchrealm/kachery-cloud#28]
I added a personal access token with repo permissions, but I get this error back:

```
Checking...
Traceback (most recent call last):
  File "/Users/dan/proj/kachery/.venv/bin/kachery-cloud-init", line 33, in <module>
    sys.exit(load_entry_point('kachery-cloud==0.4.10', 'console_scripts', 'kachery-cloud-init')())
  File "/Users/dan/proj/kachery/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dan/proj/kachery/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/dan/proj/kachery/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dan/proj/kachery/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dan/proj/kachery/.venv/lib/python3.10/site-packages/kachery_cloud/cli.py", line 13, in init
    kc.init()
  File "/Users/dan/proj/kachery/.venv/lib/python3.10/site-packages/kachery_cloud/init.py", line 82, in init
    raise Exception('Failed to initialize this kachery client')
Exception: Failed to initialize this kachery client
```

Any suggestions?

**Comment by dbirman** [comment]
Nevermind I didn't see that there was another step where you had to click "register client" in the gateaway to complete that.
